### ISSUE TITLE
Port updated for Knative/Istio

### ISSUE THREAD

**Issue by howard86** [vfarcic/devops-catalog-code#52]
On devops-catalog-code/knative/istio/devops-toolkit.yaml, it should be port `80` instead of port `8080` 

Reference:
- [gist](https://gist.github.com/vfarcic/dc4ba562328c1d088047884026371f1f#file-04-03-knative-sh-L84)

**Comment by vfarcic** [comment]
Thanks for that. I must have changed the image and forgotten to change that manifest. It's fixed now :)
